name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: Compile
        run: mvn clean compile
      - name: Test
        run: mvn clean test
